### PR TITLE
add arabic language

### PR DESCRIPTION
**Pull request by hamzamg**

### CODE REVIEW

**Comment by umutcanbolat** [comment]
Hi! If you also provide your translations in `ar.json` in [translations](https://github.com/instant-username-search/instant-username-search/tree/master/src/translations) folder, I can merge this PR. Thanks.

**Comment by umutcanbolat** [comment]
Hi! If you can provide your translations in ar.json in the translations folder, I can merge this PR. Thanks.

**Comment by umutcanbolat** [comment]
Hi! If you can provide your translations in `ar.json` in the [translations](https://github.com/instant-username-search/instant-username-search/tree/master/src/translations) folder, I can merge this PR. Thanks.

**Comment by hamzamg** [comment]
i can't add a nother file ar.json

**Pull request closed without merging**
